# Generated by Django 2.2.6 on 2019-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('-question',)},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='catagory',
        ),
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='qs',
            field=models.ManyToManyField(to='quiz.Questions'),
        ),
    ]
