# Generated by Django 2.2.6 on 2019-10-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20191006_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-quiz_name',)},
        ),
    ]
