# Generated by Django 2.2.6 on 2019-10-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_userfullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFullName',
        ),
    ]
