# Generated by Django 2.2.6 on 2019-10-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='quiz_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz'),
        ),
    ]
