# Generated by Django 2.2.6 on 2019-10-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20191006_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='Quiz_name',
            new_name='noq',
        ),
    ]
